package com.hori.model;
//Generated 2017-6-22 19:39:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* Menu generated by hbm2java
*/
@Entity
@Table(name = "menu", catalog = "grms_ums")
public class Menu implements java.io.Serializable {

	private String menuId;
	private String systemId;
	private String menuCode;
	private String menuParentId;
	private String menuname;
	private Byte menuApp;
	private String menuUrl;
	private String menuIcon;
	private Byte menuStatus;
	private Byte menuOrder;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public Menu() {
	}

	public Menu(String menuId) {
		this.menuId = menuId;
	}

	public Menu(String menuId, String systemId, String menuCode, String menuParentId, String menuname, Byte menuApp,
			String menuUrl, String menuIcon, Byte menuStatus, Byte menuOrder, Date createTime, Date modifiedTime,
			String note) {
		this.menuId = menuId;
		this.systemId = systemId;
		this.menuCode = menuCode;
		this.menuParentId = menuParentId;
		this.menuname = menuname;
		this.menuApp = menuApp;
		this.menuUrl = menuUrl;
		this.menuIcon = menuIcon;
		this.menuStatus = menuStatus;
		this.menuOrder = menuOrder;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "menu_id", unique = true, nullable = false, length = 32)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "menu_code", length = 50)
	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	@Column(name = "menu_parent_id", length = 32)
	public String getMenuParentId() {
		return this.menuParentId;
	}

	public void setMenuParentId(String menuParentId) {
		this.menuParentId = menuParentId;
	}

	@Column(name = "menuname", length = 100)
	public String getMenuname() {
		return this.menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	@Column(name = "menu_app")
	public Byte getMenuApp() {
		return this.menuApp;
	}

	public void setMenuApp(Byte menuApp) {
		this.menuApp = menuApp;
	}

	@Column(name = "menu_url", length = 300)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "menu_icon", length = 50)
	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	@Column(name = "menu_status")
	public Byte getMenuStatus() {
		return this.menuStatus;
	}

	public void setMenuStatus(Byte menuStatus) {
		this.menuStatus = menuStatus;
	}

	@Column(name = "menu_order")
	public Byte getMenuOrder() {
		return this.menuOrder;
	}

	public void setMenuOrder(Byte menuOrder) {
		this.menuOrder = menuOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
