package com.hori.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "grms_ums", uniqueConstraints = @UniqueConstraint(columnNames = "area_id"))
public class Area implements java.io.Serializable {

	private String areaUuid;
	private String systemId;
	private String provinceId;
	private String provinceName;
	private String cityId;
	private String cityName;
	private String areaName;
	private String areaId;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public Area() {
	}

	public Area(String areaUuid, String areaName) {
		this.areaUuid = areaUuid;
		this.areaName = areaName;
	}

	public Area(String areaUuid, String systemId, String provinceId, String provinceName, String cityId,
			String cityName, String areaName, String areaId, Date createTime, Date modifiedTime, String note) {
		this.areaUuid = areaUuid;
		this.systemId = systemId;
		this.provinceId = provinceId;
		this.provinceName = provinceName;
		this.cityId = cityId;
		this.cityName = cityName;
		this.areaName = areaName;
		this.areaId = areaId;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id

	@Column(name = "area_uuid", unique = true, nullable = false, length = 32)
	public String getAreaUuid() {
		return this.areaUuid;
	}

	public void setAreaUuid(String areaUuid) {
		this.areaUuid = areaUuid;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "province_id", length = 32)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "province_name", length = 100)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "city_id", length = 32)
	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	@Column(name = "city_name", length = 100)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "area_name", nullable = false, length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "area_id", unique = true, length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
