package com.hori.model;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "grms_ums")
public class Department implements java.io.Serializable {

	private String departId;
	private String departName;
	private String systemId;
	private String departParentId;
	private String departCode;
	private String departDesc;
	private Date createTime;
	private Date modifiedTime;
	private String note;
	
	private  List<Department>  departmentList;


	public Department() {
	}

	public Department(String departId, String departName, String systemId) {
		this.departId = departId;
		this.departName = departName;
		this.systemId = systemId;
	}

	public Department(String departId, String departName, String systemId, String departParentId, String departCode,
			String departDesc, Date createTime, Date modifiedTime, String note) {
		this.departId = departId;
		this.departName = departName;
		this.systemId = systemId;
		this.departParentId = departParentId;
		this.departCode = departCode;
		this.departDesc = departDesc;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
    @GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
    @GeneratedValue(generator = "system-uuid")
	@Column(name = "depart_id", unique = true, nullable = false, length = 32)
	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	@Column(name = "depart_name", nullable = false, length = 100)
	public String getDepartName() {
		return this.departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	@Column(name = "system_id", nullable = false, length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "depart_parent_id", length = 32)
	public String getDepartParentId() {
		return this.departParentId;
	}

	public void setDepartParentId(String departParentId) {
		this.departParentId = departParentId;
	}

	@Column(name = "depart_code", length = 50)
	public String getDepartCode() {
		return this.departCode;
	}

	public void setDepartCode(String departCode) {
		this.departCode = departCode;
	}

	@Column(name = "depart_desc", length = 500)
	public String getDepartDesc() {
		return this.departDesc;
	}

	public void setDepartDesc(String departDesc) {
		this.departDesc = departDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	@Transient
	public List<Department> getDepartmentList() {
		return departmentList;
	}

	public void setDepartmentList(List<Department> departmentList) {
		this.departmentList = departmentList;
	}
	
	

}