package com.hori.model;
// Generated 2017-1-17 17:15:39 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Paramter generated by hbm2java
 */
@Entity
@Table(name="paramter")
public class Paramter  implements java.io.Serializable {


     private String id;
     private short type;
     private short code;
     private String name;
     private String value;
     private String order;
     private String enable;

    public Paramter() {
    }

	
    public Paramter(String id, short type, short code, String value) {
        this.id = id;
        this.type = type;
        this.code = code;
        this.value = value;
    }
    public Paramter(String id, short type, short code, String name, String value) {
       this.id = id;
       this.type = type;
       this.code = code;
       this.name = name;
       this.value = value;
    }
   
    @Id
    @GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
    @GeneratedValue(generator = "system-uuid")
    @Column(name="id", nullable=false, insertable=true, updatable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false)
    public short getType() {
        return this.type;
    }
    
    public void setType(short type) {
        this.type = type;
    }

    
    @Column(name="code", nullable=false)
    public short getCode() {
        return this.code;
    }
    
    public void setCode(short code) {
        this.code = code;
    }

    
    @Column(name="name", length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="value", nullable=false, length=32)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    @Column(name="order")
	public String getOrder() {
		return order;
	}


	public void setOrder(String order) {
		this.order = order;
	}

	@Column(name="enable")
	public String getEnable() {
		return enable;
	}


	public void setEnable(String enable) {
		this.enable = enable;
	}
}


