package com.hori.model;

//Generated 2017-5-24 14:50:07 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* Role generated by hbm2java
*/
@Entity
@Table(name = "role", catalog = "grms_ums")
public class Role implements java.io.Serializable {

	private String roleId;
	private String systemId;
	private String roleName;
	private Byte roleType;

	private String createAccount;
	private String note;
	private Date createTime;
	private Date modifiedTime;

	public Role() {
	}

	public Role(String roleId, String roleName, Date createTime, Date modifiedTime) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
	}

	public Role(String roleId, String systemId, String roleName, String createAccount, String note, Date createTime,
			Date modifiedTime) {
		this.roleId = roleId;
		this.systemId = systemId;
		this.roleName = roleName;
		this.createAccount = createAccount;
		this.note = note;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "role_id", unique = true, nullable = false, length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "role_name", nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_Type")
	public Byte getRoleType() {
		return roleType;
	}

	public void setRoleType(Byte roleType) {
		this.roleType = roleType;
	}

	@Column(name = "create_account", length = 100)
	public String getCreateAccount() {
		return this.createAccount;
	}

	public void setCreateAccount(String createAccount) {
		this.createAccount = createAccount;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

}
