package com.hori.model;
// Generated 2017-5-25 15:11:00 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemAdmin generated by hbm2java
 */
@Entity
@Table(name = "system_admin", catalog = "grms_ums")
public class SystemAdmin implements java.io.Serializable {

	private String systemId;
	private String systemKey;
	private String systemName;
	private byte systemStatus;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public SystemAdmin() {
	}

	public SystemAdmin(String systemId, String systemName, byte systemStatus) {
		this.systemId = systemId;
		this.systemName = systemName;
		this.systemStatus = systemStatus;
	}

	public SystemAdmin(String systemId, String systemKey, String systemName, byte systemStatus, Date createTime,
			Date modifiedTime, String note) {
		this.systemId = systemId;
		this.systemKey = systemKey;
		this.systemName = systemName;
		this.systemStatus = systemStatus;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id

	@Column(name = "system_id", unique = true, nullable = false, length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "system_key", length = 100)
	public String getSystemKey() {
		return this.systemKey;
	}

	public void setSystemKey(String systemKey) {
		this.systemKey = systemKey;
	}

	@Column(name = "system_name", nullable = false, length = 100)
	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	@Column(name = "system_status", nullable = false)
	public byte getSystemStatus() {
		return this.systemStatus;
	}

	public void setSystemStatus(byte systemStatus) {
		this.systemStatus = systemStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}