package com.hori.model;
//Generated 2017-6-9 15:59:02 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* UserDetail generated by hbm2java
*/
@Entity
@Table(name = "user_detail", catalog = "grms_ums")
public class UserDetail implements java.io.Serializable {
	/**
	 * 用户资料ID
	 */
	private String userDetailId;
	/**
	 * 部门ID
	 */
	private String departId;
	/**
	 * 部门名称
	 */
	private String departName;
	/**
	 * 用户ID(保留暂时用不到)
	 */
	private String userId;
	/**
	 * 性别
	 */
	private Character sex;
	/**
	 * 职位
	 */
	private String post;
	/**
	 * 邮件
	 */
	private String email;
	/**
	 * 手机
	 */
	private String mobile;
	/**
	 * 姓名
	 */
	private String name;
	/**
	 * 地址
	 */
	private String address;
	/**
	 * 用户昵称
	 */
	private String nickname;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public UserDetail() {
	}

	public UserDetail(String userDetailId, String userId, Date createTime, Date modifiedTime) {
		this.userDetailId = userDetailId;
		this.userId = userId;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
	}

	public UserDetail(String userDetailId, String departId, String departName, String userId, Character sex,
			String post, String email, String mobile, String name, String address, String nickname, Date createTime,
			Date modifiedTime, String note) {
		this.userDetailId = userDetailId;
		this.departId = departId;
		this.departName = departName;
		this.userId = userId;
		this.sex = sex;
		this.post = post;
		this.email = email;
		this.mobile = mobile;
		this.name = name;
		this.address = address;
		this.nickname = nickname;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "user_detail_id", unique = true, nullable = false, length = 32)
	public String getUserDetailId() {
		return this.userDetailId;
	}

	public void setUserDetailId(String userDetailId) {
		this.userDetailId = userDetailId;
	}

	@Column(name = "depart_id", length = 32)
	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	@Column(name = "depart_name", length = 100)
	public String getDepartName() {
		return this.departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	@Column(name = "user_id",  length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "post", length = 100)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "nickname", length = 100)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
