package com.hori.dao.queryBean;
// Generated 2017-1-13 11:16:21 by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Contract generated by hbm2java
 */

public class ContractQueryBean  extends BaseQueryBean {


     /**
	 * 
	 */
	private String id;
     private String name;
     private String customerId;
     private String customerName;
     private String contractNumber;
     private String contractNumberId;
     private String proxy;
     private Date signDate;
     private String handler;
     private String approver;
     private byte type;
     private BigDecimal totalMoney;
     private BigDecimal entityMoney;
     private BigDecimal appMoney;
     private BigDecimal guardScreenMoney;
     private BigDecimal cashMoeny;
     private BigDecimal guardCardMoney;
     private BigDecimal promotionActiveMoney;
     private BigDecimal otherActiveMoney;
     private Date beginTime;
     private Date endTime;
     private String moneyStatus;
     private String goodStatus;
     private String attchmentId;
     private Date createTime;
     private Date modifiedTime;
     private String levelNo;

    public ContractQueryBean() {
    }

	
    public ContractQueryBean(String id, String name, String customerId, String contractNumber, String contractNumberId, byte type) {
        this.id = id;
        this.name = name;
        this.customerId = customerId;
        this.contractNumber = contractNumber;
        this.contractNumberId = contractNumberId;
        this.type = type;
    }
    public ContractQueryBean(String id, String name, String customerId, String contractNumber, String contractNumberId, String proxy, Date signDate, String handler, String approver, byte type,BigDecimal totalMoney,BigDecimal entityMoney, BigDecimal appMoney, BigDecimal guardScreenMoney, BigDecimal cashMoeny, BigDecimal guardCardMoney, BigDecimal promotionActiveMoney, BigDecimal otherActiveMoney, Date beginTime, Date endTime, String moneyStatus, String goodStatus, String attchmentId, Date createTime, Date modifiedTime,String levelNo) {
       this.id = id;
       this.name = name;
       this.customerId = customerId;
       this.contractNumber = contractNumber;
       this.contractNumberId = contractNumberId;
       this.proxy = proxy;
       this.signDate = signDate;
       this.handler = handler;
       this.approver = approver;
       this.type = type;
       this.totalMoney = totalMoney;
       this.entityMoney = entityMoney;
       this.appMoney = appMoney;
       this.guardScreenMoney = guardScreenMoney;
       this.cashMoeny = cashMoeny;
       this.guardCardMoney = guardCardMoney;
       this.promotionActiveMoney = promotionActiveMoney;
       this.otherActiveMoney = otherActiveMoney;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.moneyStatus = moneyStatus;
       this.goodStatus = goodStatus;
       this.attchmentId = attchmentId;
       this.createTime = createTime;
       this.modifiedTime = modifiedTime;
       this.levelNo = levelNo;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    
    public String getCustomerName() {
        return customerName;
    }


    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    
    public String getContractNumber() {
        return this.contractNumber;
    }
    
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    
    public String getContractNumberId() {
        return this.contractNumberId;
    }
    
    public void setContractNumberId(String contractNumberId) {
        this.contractNumberId = contractNumberId;
    }

    
    public String getProxy() {
        return this.proxy;
    }
    
    public void setProxy(String proxy) {
        this.proxy = proxy;
    }

    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    
    public String getHandler() {
        return this.handler;
    }
    
    public void setHandler(String handler) {
        this.handler = handler;
    }

    
    public String getApprover() {
        return this.approver;
    }
    
    public void setApprover(String approver) {
        this.approver = approver;
    }

    
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    

    public BigDecimal getTotalMoney() {
        return totalMoney;
    }


    public void setTotalMoney(BigDecimal totalMoney) {
        this.totalMoney = totalMoney;
    }

    
    public BigDecimal getEntityMoney() {
        return this.entityMoney;
    }
    
    public void setEntityMoney(BigDecimal entityMoney) {
        this.entityMoney = entityMoney;
    }

    
    public BigDecimal getAppMoney() {
        return this.appMoney;
    }
    
    public void setAppMoney(BigDecimal appMoney) {
        this.appMoney = appMoney;
    }

    
    public BigDecimal getGuardScreenMoney() {
        return this.guardScreenMoney;
    }
    
    public void setGuardScreenMoney(BigDecimal guardScreenMoney) {
        this.guardScreenMoney = guardScreenMoney;
    }

    
    public BigDecimal getCashMoeny() {
        return this.cashMoeny;
    }
    
    public void setCashMoeny(BigDecimal cashMoeny) {
        this.cashMoeny = cashMoeny;
    }

    
    public BigDecimal getGuardCardMoney() {
        return this.guardCardMoney;
    }
    
    public void setGuardCardMoney(BigDecimal guardCardMoney) {
        this.guardCardMoney = guardCardMoney;
    }

    
    public BigDecimal getPromotionActiveMoney() {
        return this.promotionActiveMoney;
    }
    
    public void setPromotionActiveMoney(BigDecimal promotionActiveMoney) {
        this.promotionActiveMoney = promotionActiveMoney;
    }

    
    public BigDecimal getOtherActiveMoney() {
        return this.otherActiveMoney;
    }
    
    public void setOtherActiveMoney(BigDecimal otherActiveMoney) {
        this.otherActiveMoney = otherActiveMoney;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    public String getMoneyStatus() {
        return this.moneyStatus;
    }
    
    public void setMoneyStatus(String moneyStatus) {
        this.moneyStatus = moneyStatus;
    }

    
    public String getGoodStatus() {
        return this.goodStatus;
    }
    
    public void setGoodStatus(String goodStatus) {
        this.goodStatus = goodStatus;
    }

    
    public String getAttchmentId() {
        return this.attchmentId;
    }
    
    public void setAttchmentId(String attchmentId) {
        this.attchmentId = attchmentId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifiedTime() {
        return this.modifiedTime;
    }
    
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
    
    public String getLevelNo() {
        return levelNo;
    }


    public void setLevelNo(String levelNo) {
        this.levelNo = levelNo;
    }


    @Override
    public String toString() {
        return "Contract [id=" + id + ", name=" + name + ", customerId=" + customerId + ", contractNumber="
                + contractNumber + ", contractNumberId=" + contractNumberId + ", proxy=" + proxy
                + ", signDate=" + signDate + ", handler=" + handler + ", approver=" + approver + ", type="
                + type + ", totalMoney=" + totalMoney + ", entityMoney=" + entityMoney + ", appMoney="
                + appMoney + ", guardScreenMoney=" + guardScreenMoney + ", cashMoeny=" + cashMoeny
                + ", guardCardMoney=" + guardCardMoney + ", promotionActiveMoney=" + promotionActiveMoney
                + ", otherActiveMoney=" + otherActiveMoney + ", beginTime=" + beginTime + ", endTime="
                + endTime + ", moneyStatus=" + moneyStatus + ", goodStatus=" + goodStatus + ", attchmentId="
                + attchmentId + ", createTime=" + createTime + ", modifiedTime=" + modifiedTime
                + ", levelNo=" + levelNo + "]";
    }

}


