package com.hori.dao.queryBean;
// Generated 2017-1-13 11:16:21 by Hibernate Tools 4.3.1.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ContractNumber generated by hbm2java
 */
public class ContractNumberQueryBean extends BaseQueryBean {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
     private String number;
     private Short type;
     private String relation;
     private Date createTime;
     private String levelNo;

    public ContractNumberQueryBean() {
    }

	
    public ContractNumberQueryBean(String id) {
        this.id = id;
    }
    public ContractNumberQueryBean(String id, String number, Short type, String relation, Date createTime, String levelNo) {
       this.id = id;
       this.number = number;
       this.type = type;
       this.relation = relation;
       this.createTime = createTime;
       this.levelNo = levelNo ;
    }
   
    
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }

    
    public String getRelation() {
        return this.relation;
    }
    
    public void setRelation(String relation) {
        this.relation = relation;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public String getLevelNo() {
        return levelNo;
    }


    public void setLevelNo(String levelNo) {
        this.levelNo = levelNo;
    }


    @Override
    public String toString() {
        return "ContractNumber [id=" + id + ", number=" + number + ", type=" + type + ", relation="
                + relation + ", createTime=" + createTime + ", levelNo=" + levelNo + "]";
    }

   
    
}


