package com.hori.model;
//Generated 2017-6-15 14:55:33 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* AuthorizeArea generated by hbm2java
*/
@Entity
@Table(name = "authorize_area", catalog = "grms_ums")
public class AuthorizeArea implements java.io.Serializable {
	/**
	 * 用户责任范围ID
	 */
	private String authorizeAreaId;
	/**
	 * 所属系统ID
	 */
	private String systemId;
	/**
	 * 用户ID
	 */
	private String userId;
	/**
	 * 省编码
	 */
	private String provinceId;
	/**
	 * 省名称
	 */
	private String provinceName;
	/**
	 * 市编码
	 */
	private String cityId;
	/**
	 * 市名称
	 */
	private String cityName;
	/**
	 * 区名称
	 */
	private String areaName;
	/**
	 * 区编码
	 */
	private String areaId;
	
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public AuthorizeArea() {
	}

	public AuthorizeArea(String authorizeAreaId, String userId, String areaName) {
		this.authorizeAreaId = authorizeAreaId;
		this.userId = userId;
		this.areaName = areaName;
	}

	public AuthorizeArea(String authorizeAreaId, String systemId, String userId, String provinceId, String provinceName,
			String cityId, String cityName, String areaName, String areaId, Date createTime, Date modifiedTime,
			String note) {
		this.authorizeAreaId = authorizeAreaId;
		this.systemId = systemId;
		this.userId = userId;
		this.provinceId = provinceId;
		this.provinceName = provinceName;
		this.cityId = cityId;
		this.cityName = cityName;
		this.areaName = areaName;
		this.areaId = areaId;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "authorize_area_id", unique = true, nullable = false, length = 32)
	public String getAuthorizeAreaId() {
		return this.authorizeAreaId;
	}

	public void setAuthorizeAreaId(String authorizeAreaId) {
		this.authorizeAreaId = authorizeAreaId;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "user_id", nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "province_id", length = 32)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "province_name", length = 100)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "city_id", length = 32)
	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	@Column(name = "city_name", length = 100)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "area_name", nullable = false, length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "area_id", length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
