package com.hori.model;
//Generated 2017-6-22 19:39:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* Operation generated by hbm2java
*/
@Entity
@Table(name = "operation", catalog = "grms_ums")
public class Operation implements java.io.Serializable {

	private String btnId;
	private String menuId;
	private String btnParentId;
	private String btnCode;
	private String btnUrl;
	private String btnIcon;
	private Byte btnApp;
	private Byte btnStatus;
	private Byte btnOrder;
	private String btnName;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public Operation() {
	}

	public Operation(String btnId, String menuId) {
		this.btnId = btnId;
		this.menuId = menuId;
	}

	public Operation(String btnId, String menuId, String btnParentId, String btnCode, String btnUrl, String btnIcon,
			Byte btnApp, Byte btnStatus, Byte btnOrder, String btnName, Date createTime, Date modifiedTime,
			String note) {
		this.btnId = btnId;
		this.menuId = menuId;
		this.btnParentId = btnParentId;
		this.btnCode = btnCode;
		this.btnUrl = btnUrl;
		this.btnIcon = btnIcon;
		this.btnApp = btnApp;
		this.btnStatus = btnStatus;
		this.btnOrder = btnOrder;
		this.btnName = btnName;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "btn_id", unique = true, nullable = false, length = 32)
	public String getBtnId() {
		return this.btnId;
	}

	public void setBtnId(String btnId) {
		this.btnId = btnId;
	}

	@Column(name = "menu_id", nullable = false, length = 32)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "btn_parent_id", length = 32)
	public String getBtnParentId() {
		return this.btnParentId;
	}

	public void setBtnParentId(String btnParentId) {
		this.btnParentId = btnParentId;
	}

	@Column(name = "btn_code", length = 50)
	public String getBtnCode() {
		return this.btnCode;
	}

	public void setBtnCode(String btnCode) {
		this.btnCode = btnCode;
	}

	@Column(name = "btn_url", length = 3000)
	public String getBtnUrl() {
		return this.btnUrl;
	}

	public void setBtnUrl(String btnUrl) {
		this.btnUrl = btnUrl;
	}

	@Column(name = "btn_icon", length = 50)
	public String getBtnIcon() {
		return this.btnIcon;
	}

	public void setBtnIcon(String btnIcon) {
		this.btnIcon = btnIcon;
	}

	@Column(name = "btn_app")
	public Byte getBtnApp() {
		return this.btnApp;
	}

	public void setBtnApp(Byte btnApp) {
		this.btnApp = btnApp;
	}

	@Column(name = "btn_status")
	public Byte getBtnStatus() {
		return this.btnStatus;
	}

	public void setBtnStatus(Byte btnStatus) {
		this.btnStatus = btnStatus;
	}

	@Column(name = "btn_order")
	public Byte getBtnOrder() {
		return this.btnOrder;
	}

	public void setBtnOrder(Byte btnOrder) {
		this.btnOrder = btnOrder;
	}

	@Column(name = "btn_name", length = 100)
	public String getBtnName() {
		return this.btnName;
	}

	public void setBtnName(String btnName) {
		this.btnName = btnName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 300)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}