package com.hori.model;

//Generated 2017-6-1 10:23:07 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
* User generated by hbm2java
*/
@Entity
@Table(name = "user", catalog = "grms_ums")
public class User implements java.io.Serializable {
	/**
	 * 用户ID
	 */
	private String userId;
	/**
	 * 用户资料ID
	 */
	private String userDetailId;
	/**
	 * 用户帐号
	 */
	private String userAccount;
	/**
	 * 手机(不是必填项考虑后面可能会用到手机登录)
	 */
	private String mobile;
	/**
	 * 密码
	 */
	private String password;
	/**
	 * 用户状态 帐号的状态 0 表示帐号失效 1 表示帐号可用
	 */
	private Byte status;
	/**
	 * 用户类型
	 */
	private Byte userType;
	/**
	 * 用户所属系统
	 */
	private String systemId;
	/**
	 * 用户数据域0 表示个人数据 1 表示部门数据 2表示全局数据
	 */
	private Byte dataArea;

	private String dr;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public User() {
	}

	public User(String userId, String userAccount, String password, Date createTime, Date modifiedTime) {
		this.userId = userId;
		this.userAccount = userAccount;
		this.password = password;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
	}

	public User(String userId, String userDetailId, String userAccount, String mobile, String password, Byte status,
			Byte userType, String systemId, Date createTime, Date modifiedTime, String note) {
		this.userId = userId;
		this.userDetailId = userDetailId;
		this.userAccount = userAccount;
		this.mobile = mobile;
		this.password = password;
		this.status = status;
		this.userType = userType;
		this.systemId = systemId;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "user_id", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_detail_id", length = 32)
	public String getUserDetailId() {
		return this.userDetailId;
	}

	public void setUserDetailId(String userDetailId) {
		this.userDetailId = userDetailId;
	}

	@Column(name = "user_account", nullable = false, length = 100)
	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}
	@Column(name = "data_area")
	public Byte getDataArea() {
		return dataArea;
	}

	public void setDataArea(Byte dataArea) {
		this.dataArea = dataArea;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "user_type")
	public Byte getUserType() {
		return this.userType;
	}

	public void setUserType(Byte userType) {
		this.userType = userType;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	@Column(name = "dr", length = 1)
	public String getDr() {
		return dr;
	}

	public void setDr(String dr) {
		this.dr = dr;
	}

}
