/***********************************************************************
 * Module:  DeptManage.java
 * Author:  daihf
 * Purpose: Defines the Class DeptManage
 ***********************************************************************/

package com.hori.model;

//Generated 2017-5-31 14:49:23 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Area generated by hbm2java
*/
@Entity
@Table(name = "area_system", catalog = "grms_ums")
public class AreaSystem implements java.io.Serializable {

	private String areaId;
	private String systemId;
	private String areaName;
	private String areaParentId;
	private String areaCode;
	private String areaDesc;
	private Date createTime;
	private Date modifiedTime;
	private String note;

	public AreaSystem() {
	}

	public AreaSystem(String areaId, String areaName) {
		this.areaId = areaId;
		this.areaName = areaName;
	}

	public AreaSystem(String areaId, String systemId, String areaName, String areaParentId, String areaCode, String areaDesc,
			Date createTime, Date modifiedTime, String note) {
		this.areaId = areaId;
		this.systemId = systemId;
		this.areaName = areaName;
		this.areaParentId = areaParentId;
		this.areaCode = areaCode;
		this.areaDesc = areaDesc;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id

	@Column(name = "area_id", unique = true, nullable = false, length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Column(name = "system_id", length = 32)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@Column(name = "area_name", nullable = false, length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "area_parent_id", length = 32)
	public String getAreaParentId() {
		return this.areaParentId;
	}

	public void setAreaParentId(String areaParentId) {
		this.areaParentId = areaParentId;
	}

	@Column(name = "area_code", length = 50)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "area_desc", length = 500)
	public String getAreaDesc() {
		return this.areaDesc;
	}

	public void setAreaDesc(String areaDesc) {
		this.areaDesc = areaDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}