package com.hori.model;
//Generated 2017-6-22 19:39:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
* Author generated by hbm2java
*/
@Entity
@Table(name = "author", catalog = "grms_ums")
public class Author implements java.io.Serializable {

	private String authorId;
	private String roleId;
	private String resourceParentId;
	private String resourceId;
	private String resourceMenuId;
	private String resourceDesc;
	private Integer resourceApp;
	private Integer resourseOrder;
	private String resourseIcon;
	private String resourceCode;
	private String resourceUrl;
	private Short resourseType;
	private Date createTime;
	private Date modifiedTime;
	private String note;
	private  List<Author>  authVoList;
	public Author() {
	}

	public Author(String authorId) {
		this.authorId = authorId;
	}

	public Author(String authorId, String roleId, String resourceParentId, String resourceId, String resourceMenuId,
			String resourceDesc, Integer resourceApp, Integer resourseOrder, String resourseIcon, String resourceCode,
			String resourceUrl, Short resourseType, Date createTime, Date modifiedTime, String note) {
		this.authorId = authorId;
		this.roleId = roleId;
		this.resourceParentId = resourceParentId;
		this.resourceId = resourceId;
		this.resourceMenuId = resourceMenuId;
		this.resourceDesc = resourceDesc;
		this.resourceApp = resourceApp;
		this.resourseOrder = resourseOrder;
		this.resourseIcon = resourseIcon;
		this.resourceCode = resourceCode;
		this.resourceUrl = resourceUrl;
		this.resourseType = resourseType;
		this.createTime = createTime;
		this.modifiedTime = modifiedTime;
		this.note = note;
	}

	@Id
	@GenericGenerator(name = "system-uuid", strategy = "com.hori.hibernate.UUIDGenerator")
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "author_id", unique = true, nullable = false, length = 32)
	public String getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(String authorId) {
		this.authorId = authorId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "resource_parent_id", length = 32)
	public String getResourceParentId() {
		return this.resourceParentId;
	}

	public void setResourceParentId(String resourceParentId) {
		this.resourceParentId = resourceParentId;
	}

	@Column(name = "resource_id", length = 32)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "resource_menu_id", length = 32)
	public String getResourceMenuId() {
		return this.resourceMenuId;
	}

	public void setResourceMenuId(String resourceMenuId) {
		this.resourceMenuId = resourceMenuId;
	}

	@Column(name = "resource_desc", length = 400)
	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	@Column(name = "resource_app")
	public Integer getResourceApp() {
		return this.resourceApp;
	}

	public void setResourceApp(Integer resourceApp) {
		this.resourceApp = resourceApp;
	}

	@Column(name = "resourse_order")
	public Integer getResourseOrder() {
		return this.resourseOrder;
	}

	public void setResourseOrder(Integer resourseOrder) {
		this.resourseOrder = resourseOrder;
	}

	@Column(name = "resourse_icon", length = 100)
	public String getResourseIcon() {
		return this.resourseIcon;
	}

	public void setResourseIcon(String resourseIcon) {
		this.resourseIcon = resourseIcon;
	}

	@Column(name = "resource_code", length = 100)
	public String getResourceCode() {
		return this.resourceCode;
	}

	public void setResourceCode(String resourceCode) {
		this.resourceCode = resourceCode;
	}

	@Column(name = "resource_url", length = 3000)
	public String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	@Column(name = "resourse_type")
	public Short getResourseType() {
		return this.resourseType;
	}

	public void setResourseType(Short resourseType) {
		this.resourseType = resourseType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	@Transient
	public List<Author> getAuthVoList() {
		return authVoList;
	}

	public void setAuthVoList(List<Author> authVoList) {
		this.authVoList = authVoList;
	}

	
}
